import type { Metadata } from "next";

import "./globals.css";

import localFont from "next/font/local";
import { Toaster } from "sonner";

const myFont = localFont({
  src: "../lib/font/Outfit-Variable.ttf",
  display: "swap",
  variable: "--my-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${myFont.className} antialiased text-balance`}>
        <Toaster richColors position="top-right" />
        {children}
      </body>
    </html>
  );
}
